name: Deploy
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH connection and environment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            echo "This one will work!"
            whoami
            hostname
            pwd
            ls -la ./deploy-pz-scoreboard.sh || echo "script not found at relative path"
            id
            env | sort
